# Site settings 配置站点
title: 'Erodeveil ∅'
description: 'A study in erosion and emergence.'
keyword: ''
url: 'https://www.erodeveil.cyou/'

# when build blog on server, if you don't need baseurl, you should leave this value blank.
# 在服务器上建站时，如果你不需要子域名，请将这一格留空
# if you're using GitHub Pages, set baseurl to your blog's .
# 如果你在使用 GitHub Pages, 请将 baseurl 设置为你的网址的子域名
# for example, if your site is "kaeyleo.github.io", then this url should leave blank.
# 例如，当你的域名是 "kaeyleo.github.io"  时，这个 url 需要留空
# but if your created a repo named "myblog", and the site is "kaeyleo.github.io/myblog", change baseurl to '/myblog'
# 但是，如果你创建了一个叫 "myblog" 的网站，此时网址会变成 "kaeyleo.github.io/myblog" ，这时再将 baseurl 设置为 '/myblog'
baseurl: ''
theme: jekyll-theme-h2o-ac

# Internalization 国际化
languages: ["zh-Hans", "zh-Hant", "en", "ja"]
default_lang: "zh-Hans"

# PWA
pwa:
  color: '#81BBFF'
  short_name: 'TeRv'

# Navigation links
nav:
  home: '/'
  blog: '/blog/index.html'
  archives: '/archives.html'
  tags: '/tags.html'
  about:   
    logs: '/logs.html'
    tos: '/tos.html'
    RSS: '/feed.xml'
    CV: '/cv.html'
    links: '/links.html'

# Gray for the whole site 全站灰色
gray: false

# Formats
# 时间格式（Time format）：0 -- 2022-04-29    1 -- 29 Apr 2022   2 -- 2022年4月29日
formats:
  time: 2

# Favicon
favicon: "/favicon.ico"

# Footer
footer:
  since: 2026

# Author 配置博主信息
author: 'Telsolytor'
nickname: 'Telsolytor'
bio: '∅йсе uρøи α τιмё.'
avatar: 'https://youke.xn--y7xa690gmna.cn/s1/2026/02/13/698f30f756d7c.webp'

# Search
search: true

# Night mode
nightMode: false

# Comments 评论功能
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'
  waline: true
  waline_url: 'https://waline-for-terv.vercel.app/'
  waline_reaction: true  # 是否开启 Waline 表情反馈，以下为自定义本地化配置。
  waline_locale: "{reaction0: '赞一个', reaction1: '踩一下', reaction2: '有点酷', reaction3: '看不懂', reaction4: '啥玩意', reaction5: '想睡觉'}"

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'seaOfClouds'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: 'https://github.com/Telsolytor'
  twitter: 'https://x.com/Telsolytor'
  

# Links 友情链接
links:
  'Lociwyn': 'https://x.com/lociwyn'

# Beian 备案号
beian: ''

# CC License
cclicense: true

# CNZZ Analytics
# cnzz: 1234567891
cnzz: 

# Busuanzi Analytics
busuanzi: true

# Umami Analytics
umami:
  status: true
  id: 9fb2b564-9134-4f19-8cb5-f90f5e77e1c6
  js: https://cloud.umami.is/script.js

# Google Analytics
# google_analytics: UA-XXXXXXXXX-X
# google_analytics: 
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-756SW0F13M"


# Google Search
google_search: 

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
pagination:
  enabled: true
  per_page: 10
# paginate: 10
# paginate_path: 'blog/page:num'

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
prism:
  theme:
  line_numbers: true

# RSS
RSS: true

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:categories/:title.html

# TOC
toc: true

# Mermaid
mermaid: true

# Webpusher
webpusher: false

# Foreverblog
foreverblog: false

# Wormhole
wormhole: false

# NotByAI
notbyAI: true

cloudflare: true

# Alive time
alivetime: true
alivestart: "1/13/2026"
